name = "anton2"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "188.166.183.136:443"
UUID = "822ecabb-779b-4e19-879a-c9fe1512cf67"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
